{
 "title": "One Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Outside Temperature ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Outside Temperature" }
     ]
    }
   ]
  },
  {
   "title": "Weather Summary",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "lat": "42.086185", "lon": "-88.447031", "target": "summary", "type": "timeseries" }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "speedtest-status_xput_upload" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "UDM-Pro" }
     ]
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "speedtest-status_xput_download" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "UDM-Pro" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 16, "x": 8, "y": 7 }, "options": { "content": "\n# Network Traffic\n\n\n" } },
  {
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "query": "SELECT \"num_gw\" FROM \"subsystems\" WHERE (\"site_name\" = 'Pingree Ranch (llbpbihi)' AND \"subsystem\" = 'wan') AND $timeFilter",
     "select": [
      [
       { "params": [ "num_gw" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wan" }
     ]
    }
   ]
  },
  {
   "title": "Switches",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "select": [
      [
       { "params": [ "num_sw" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "lan" }
     ]
    }
   ]
  },
  {
   "title": "WAPs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "query": "SELECT \"num_ap\" FROM \"subsystems\" WHERE (\"site_name\" = 'Default (default)' AND \"subsystem\" = 'wlan') AND $timeFilter",
     "select": [
      [
       { "params": [ "num_ap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wlan" }
     ]
    }
   ]
  },
  {
   "title": "VPN Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "select": [
      [
       { "params": [ "num_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "vpn" }
     ]
    }
   ]
  },
  {
   "title": "WLAN Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "select": [
      [
       { "params": [ "num_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wlan" }
     ]
    }
   ]
  },
  {
   "title": "WLAN IoT",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "query": "SELECT \"num_iot\" FROM \"subsystems\" WHERE (\"site_name\" = 'Pingree Ranch (default)' AND \"subsystem\" = 'wlan') AND $timeFilter",
     "select": [
      [
       { "params": [ "num_iot" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wlan" }
     ]
    }
   ]
  },
  {
   "title": "LAN Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "select": [
      [
       { "params": [ "num_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "lan" }
     ]
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "subsystems",
     "select": [
      [
       { "params": [ "num_sta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=", "value": "Default (default)" },
      { "condition": "AND", "key": "subsystem", "operator": "=", "value": "wan" }
     ]
    }
   ]
  },
  {
   "title": "Ad blocking",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "measurement": "pihole",
     "query": "SELECT last(\"status\"), \"unique_clients\", \"dns_queries_today\", \"ads_percentage_today\", \"ads_blocked_today\", \"domains_being_blocked\", \"unique_domains\" FROM \"pihole\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "dns_queries_today" ], "type": "field" }
      ],
      [
       { "params": [ "ads_percentage_today" ], "type": "field" }
      ],
      [
       { "params": [ "ads_blocked_today" ], "type": "field" }
      ],
      [
       { "params": [ "domains_being_blocked" ], "type": "field" }
      ],
      [
       { "params": [ "unique_domains" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Office Temperature ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Button" }
     ]
    }
   ]
  },
  {
   "title": "Office Temperature ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Button" }
     ]
    }
   ]
  },
  {
   "title": "Garage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Xiaomi Temp Sensor" }
     ]
    }
   ]
  },
  {
   "title": "Patio Entrance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Patio Entrance" }
     ]
    }
   ]
  },
  {
   "title": "Mudroom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Motion Sensor" }
     ]
    }
   ]
  },
  {
   "title": "Smarthings Battery Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "deviceName" ], "type": "tag" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Transcoding Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added Movies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added TV Shows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Available NAS Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "lod" }
     ]
    }
   ]
  },
  {
   "title": "Available Cache",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/cache_ssd" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "lod" }
     ]
    }
   ]
  }
 ]
}