- hosts: "*"
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: set timezone to Chicago
      shell: timedatectl set-timezone America/Chicago

- name: Update PiHole Machine
  hosts: "*52"
  become: yes
  tasks:
    - name: Check For Updates
      shell: pihole -up
    - name: Update Gravity
      shell: pihole updateGravity

- name: install latest qemu-guest-agent
  hosts: "*172"
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
